version: 0.2

phases:
  install:
    runtime-versions:
      #java: corretto17
  pre_build:
    commands:
      #- echo "Download JQ"
      #- curl -qL -o jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ./jq
      #- mv jq /usr/local/bin 
      - echo "Install Hashicorp Terraform"
      - wget https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip
      - unzip terraform_1.1.0_linux_amd64.zip
      - ls -lrt
      - pwd
      - mv terraform /usr/local/bin/
      - ls -lrt /usr/local/bin/terraform
      - terraform -v 
      - cd $CODEBUILD_SRC_DIR/hcl_terraform/
      - terraform init 
      - terraform fmt
      - terraform validate 
      - pwd
      - ls -lrta 

  build:
    commands:
      - echo "Executing Build Phase"
      - ls -lrt $CODEBUILD_SRC_DIR
      - pwd
      - ls -lrta
      - terraform -v 
      - terraform plan
      #- terraform apply -auto-approve 
  post_build:
    commands:
      - echo "Infra Job is completed on `date`"